AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A web site

Parameters:
  HostedZoneId:
    Type: String
  DomainName:
    Type: String
  BlogName:
    Type: String
  BlogDescription:
    Type: String
  AuthorName:
    Type: String
  AuthorizationEndpoint:
    Type: String
  TokenEndpoint:
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  DNSAliasV4:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName 
      HostedZoneId: !Ref HostedZoneId
      Type: A
      AliasTarget:
        DNSName: !GetAtt CDN.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  DNSAliasV6:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName 
      HostedZoneId: !Ref HostedZoneId
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt CDN.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        DefaultCacheBehavior:
          AllowedMethods: ['GET', 'HEAD']
          CachedMethods: ['GET', 'HEAD']
          Compress: true
          DefaultTTL: 31536000
          TargetOriginId: SiteBucketOrigin
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
           AcmCertificateArn: !Ref Certificate
           SslSupportMethod: sni-only
        Origins:
          - DomainName: !GetAtt SiteBucket.DualStackDomainName
            Id: SiteBucketOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only

  PageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: Data
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GS1
          Projection:
            ProjectionType: KEYS_ONLY
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: Data
              KeyType: RANGE
      KeySchema: 
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ConfigRefreshStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/config-refresh.asl.json
      DefinitionSubstitutions: 
        ListRenderablesFunction: !GetAtt ListRenderablesFunction.Arn
        RenderFunction: !GetAtt RenderFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ListRenderablesFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RenderFunction
  ListRenderablesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: list_renderables_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      Environment:
        Variables:
          TABLE: !Ref PageTable
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref PageTable
      MemorySize: 128
      Timeout: 300
  RenderFunction:    
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: render_function/
      Handler: app.lambda_handler
      Runtime: python3.8
      Description: ''
      Environment:
        Variables:
          SITE_BUCKET: !Ref SiteBucket
          BLOG_NAME: !Ref BlogName
          BLOG_DESCRIPTION: !Ref BlogDescription
          DOMAIN_NAME: !Ref DomainName
      MemorySize: 128
      Timeout: 300
    Metadata:
      BuildMethod: makefile

  BlogConfigFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: blog_config_refresh_custom_resource/
      Handler: blog_config.lambda_handler
      Runtime: python3.8
      Description: ''
      Environment:
        Variables:
          TABLE: !Ref PageTable
          STATE_MACHINE_ARN: !Ref ConfigRefreshStateMachine
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      MemorySize: 128
      Timeout: 300

  BlogConfig:
    Type: 'Custom::CustomResource'
    Properties:
      ServiceToken:
        'Fn::GetAtt':
          - BlogConfigRefreshFunction
          - Arn
    DependsOn:
      - RenderFunction